### PR TITLE
Read defines signatures

### PR DESCRIPTION
**Pull request by arthurmaciel**
@justinethier, I faced many obscure bugs and corrected all of them trying to improve the interface. 
Now `cyclone-winds package` and `cyclone-winds package-srfi` produce a much better `README.md`. 

Anyway, I would like to test the code a bit more. And I also would like to style the code according to some guidelines we have discussed before (especially aligning to approximately 80 columns - which I find quite difficult due to long strings). I would like to add a bit more tests too. 

I will work based on this branch so as soon as I finish the work and you test and merge it to master, I can send the final code. 

Thanks!

### CODE REVIEW

**Comment by arthurmaciel** [comment]
@justinethier, it would be very useful if you could test the following code:

```shell
$ cyclone-winds retrieve srfi-145
$ cyclone-winds package srfi-145
```

There is a complaint of `string-set!` related to the author name, which I don't know how to correct:
`Error: string-set! - Unable to allocate memory to store multibyte character: #\ß` 

Thanks!

**Comment by justinethier** [comment]
@arthurmaciel I am able to reproduce with the following command:

    justin@justin-OptiPlex-790 ~/Documents $ cyclone-winds info srfi-145
    Retrieving index file...
    (package
      (name srfi-145)
      (version 0.1)
      (license "MIT")
    Error: string-set! - Unable to allocate memory to store multibyte character: #\ß

So, this is due to a `string-set!` bug in the Cyclone runtime. Let me see what can be done.

I also noticed the following, it looks like the search command is broken:

    justin@justin-OptiPlex-790 ~/Documents $ cyclone-winds search srfi
    Retrieving index file...
    Error: Invalid type: expected pair, found : array-list
    Call history:
    scheme/base.sld:reverse
    scheme/base.sld:foldl
    cyclone-winds.scm:delete
    srfi/28.sld:format
    scheme/base.sld:string->list
    scheme/base.sld:foldl
    scheme/base.sld:write-char
    scheme/write.sld:display
    scheme/cyclone/util.sld:filter

**Comment by justinethier** [comment]
Also, 80 characters per line limit is not as critical as it once was. EG:
https://www.theregister.com/2020/06/01/linux_5_7/

**Comment by arthurmaciel** [comment]
Great you caught this error on `search`, @justinethier! I'll fix it.

**Comment by arthurmaciel** [comment]
With regard to styling, the argument was really convincing. I will gather the style guidelines so
we can build together something that really makes sense to Cyclone code.

**Comment by justinethier** [comment]
@arthurmaciel The lastest Cyclone code on `master` does not have the issue with multibyte chars. Would you like me to merge this pull request or should I hold off?

**Comment by arthurmaciel** [comment]
@justinethier, thanks for fixing it so quickly! Although I could merge, I think it is best practice if you review my latest commit and then merge if everything is ok.

I think the next step would be to add at least one more test (for `package-srfi`) and to modularize code. When are you planning to release `0.18`? 

Thanks!

**Comment by arthurmaciel** [comment]
@justinethier, tests fail because I added a test related to srfi-145. The rationale for including it was obvious. I tested with the new master and it works fine here. Anyway the workflow uses ubuntu binary - so it will fail until the binary is updated. If you find it inconvenient, could you please change `srfi-145` to `srfi-26` (or any other) and close the PR? Thanks

**Review by justinethier — APPROVED** [review]

**Comment by justinethier** [comment]
Looks good @arthurmaciel thanks!

I understand why the test is failing in our CI. Everything works fine on a system with the latest Cyclone though. This will be fine once everything can be released and updated.

I would like to get a new version of Cyclone out soon. How about we plan to do a release next Monday. Does that give you enough time?

**Comment by arthurmaciel** [comment]
Great, @justinethier! Thanks for carefully reviewing my code. Next Monday is a great day for the release! On Sunday I will send the last PR to close the recently opened issues.

**Comment by justinethier** [comment]
Glad to help @arthurmaciel 
Sounds like a plan :)

**Pull request merged**
